#pragma once

#include <vector>
#include <memory>
#include <atomic>
#include <glm/glm.hpp>

#include "Block.h"
#include "Constants.h"
#include "TextureAtlas.h"
#include "Shader.h"
#include "VertexArray.h"
#include "VertexBuffer.h"
#include "VertexBufferLayout.h"
#include "ChunkCoord.h"
#include "FastNoiseLite.h"
#include "TerrainGenerator.h"

class World;

struct Vertex
{
    glm::vec3 pos;
    glm::vec2 uvs;
};

struct BoundingBox
{
    glm::vec3 min;
    glm::vec3 max;
};

enum class ChunkState
{
    EMPTY,                 // Just created, no data yet
    TERRAIN_GENERATING,    // Terrain data being generated by a worker thread
    TERRAIN_GENERATED,     // Terrain data is ready, blocks array is filled
    MESH_GENERATING,       // Mesh data being generated by a worker thread
    MESH_READY_FOR_UPLOAD, // Mesh data is ready in buffer, waiting for main thread GPU upload
    LOADED,                // Fully processed, VBO/VAO set up, ready for rendering
    MESH_REGENERATING
};

class Chunk
{

public:
    ChunkCoord chunkCoord_;
    BoundingBox boundingBox_;
    ChunkState state_ = ChunkState::EMPTY;
    std::atomic<bool> isDirty_ = true;

    Chunk(Shader &shader, TextureAtlas *atlas, ChunkCoord pos, World *world_);

    void renderChunk();
    void generateMesh();
    void uploadMeshToGPU();
    void configureVertexAttributes();
    void setDirty();
    void generateTerrain();

    const Block &getBlockLocal(const glm::ivec3 &pos) const;

private:
    Shader &shader_;
    TextureAtlas *textureAtlas_;
    World *world_;
    TerrainGenerator terrainGen_;

    std::vector<Block> blocks_;
    std::vector<float> meshDataBuffer_;
    size_t vertexCount_ = 0;

    VertexArray vao_;
    VertexBuffer vbo_;

    glm::mat4 modelMatrix_;

    void generateBlockMesh(const Block &block);
    void generateFacevertices(const Block &block, BlockFaces face, const std::vector<glm::vec2> &faceUVs);
    void addBlockFace(const Block &block, const BlockType type, const BlockFaces face);

    BlockType getNeighborBlockType(const glm::ivec3 blockPos, const glm::ivec3 offset);
    inline bool blockInChunkBounds(const glm::ivec3 &pos) const;
    inline bool isTransparent(BlockType type) const;
    inline size_t getBlockIndex(const glm::ivec3 &pos) const;
};